.
├── backend
│   ├── api_doc.md
│   ├── audio
│   │   ├── plouf.mp3
│   │   ├── sample(1).mp3
│   │   ├── sample2.mp3
│   │   └── sample.mp3
│   ├── db
│   │   ├── database.go
│   │   └── migrations
│   │       ├── files.sql
│   │       ├── internal_ressources.sql
│   │       ├── messages.sql
│   │       ├── products.sql
│   │       ├── refresh_tokens.sql
│   │       ├── rooms.sql
│   │       ├── shared_ressources.sql
│   │       ├── shared_ressources_tags.sql
│   │       ├── tag.sql
│   │       ├── track.sql
│   │       └── users.sql
│   ├── go.mod
│   ├── go.sum
│   ├── handlers
│   │   ├── file.go
│   │   ├── message.go
│   │   ├── products.go
│   │   ├── ressource.go
│   │   ├── room.go
│   │   ├── search.go
│   │   ├── shared_ressources.go
│   │   ├── suggestions.go
│   │   ├── tag.go
│   │   ├── track.go
│   │   └── user.go
│   ├── handlers.zip
│   ├── internal_ressources
│   ├── main.go
│   ├── middleware
│   │   └── jwt.go
│   ├── models
│   │   ├── files.go
│   │   ├── message.go
│   │   ├── products.go
│   │   ├── ressources.go
│   │   ├── room.go
│   │   ├── shared_ressources.go
│   │   ├── suggestions.go
│   │   ├── tag.go
│   │   ├── track.go
│   │   └── user.go
│   ├── models.zip
│   ├── modules
│   │   ├── chat_server
│   │   │   ├── Cargo.lock
│   │   │   ├── Cargo.toml
│   │   │   ├── output_cargo_build
│   │   │   └── src
│   │   │       ├── auth.rs
│   │   │       ├── client.rs
│   │   │       ├── hub
│   │   │       │   ├── common.rs
│   │   │       │   ├── dm.rs
│   │   │       │   ├── mod.rs
│   │   │       │   └── room.rs
│   │   │       ├── hub.rs
│   │   │       ├── main.rs
│   │   │       └── messages.rs
│   │   └── stream_server
│   │       ├── audio
│   │       │   └── plouf.mp3
│   │       ├── Cargo.lock
│   │       ├── Cargo.toml
│   │       └── src
│   │           ├── main.rs
│   │           ├── routes.rs
│   │           └── utils.rs
│   ├── routes
│   │   ├── auth.go
│   │   ├── exchange.go
│   │   ├── file.go
│   │   ├── formation.go
│   │   ├── message.go
│   │   ├── products.go
│   │   ├── ressource.go
│   │   ├── room.go
│   │   ├── search.go
│   │   ├── shared_ressources.go
│   │   ├── suggestions.go
│   │   ├── tag.go
│   │   ├── track.go
│   │   └── user.go
│   ├── shared
│   │   ├── 2A361-68306A00-C67-4D36D880
│   │   └── secu_indus.pdf
│   ├── shared_ressources
│   │   ├── ciso_diff.png
│   │   ├── Logic_exercise.pdf
│   │   ├── login.png
│   │   ├── plouf.mp3
│   │   ├── sample(1).mp3
│   │   └── sample.mp3
│   ├── static
│   │   ├── default-avatar.png
│   │   └── favicon.ico
│   ├── uploads
│   │   └── 1_1747129598_test_upload.txt
│   └── utils
│       ├── hash.go
│       ├── jwt.go
│       └── signedurl.go
├── backend.zip
├── bordel_command_curl_test
├── frontend
│   ├── api.html
│   ├── chat.html
│   ├── css
│   │   └── style.css
│   ├── dashboard.html
│   ├── dm.html
│   ├── favicon.ico
│   ├── gg.html
│   ├── hub.html
│   ├── hub_v2.html
│   ├── js
│   │   ├── app.js
│   │   ├── dm.js
│   │   ├── message.js
│   │   ├── produits.js
│   │   ├── register.js
│   │   ├── room.js
│   │   └── users.js
│   ├── login.html
│   ├── main.html
│   ├── message.html
│   ├── plouf.html
│   ├── produits.html
│   ├── register.html
│   ├── room.html
│   ├── search.html
│   ├── search_v2.html
│   ├── shared_ressources.html
│   ├── test.html
│   ├── track.html
│   └── users.html
├── frontend.zip
├── gpts_prompts
│   └── frontend_mp_room_speration_backend_message_room.txt
├── README.md
├── ROADMAP.md
├── versions_details
│   ├── README.md
│   ├── v10_bibliotheque_personnelle_favoris
│   │   └── README.md
│   ├── v11_gestion_comptes_roles
│   │   └── README.md
│   ├── v12_standalone
│   │   └── README.md
│   ├── v1_authentification_base_utilisateurs
│   │   └── README.md
│   ├── v2_fichiers_produits_documentation
│   │   └── README.md
│   ├── v3_chat_messagerie
│   │   └── README.md
│   ├── v4_streaming_audio
│   │   └── README.md
│   ├── v5_partage_fichiers_ressources
│   │   └── README.md
│   ├── v6_moteur_recherche
│   │   └── README.md
│   ├── v7_plateforme_troc_produits
│   │   └── README.md
│   ├── v8_formation_tutoriels
│   │   └── README.md
│   └── v9_découverte_social
│       └── README.md
├── versions_details.zip
├── veza-dev.sh
└── veza-web-app_tree

39 directories, 141 files
